version: '2'
services:
  app:
    build:
      dockerfile: Dockerfile.simple
      context: .
    volumes:
      - .:/app
      - node-modules:/app/node_modules/
    working_dir: /app
    command: npm run watch
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/node_modules/.bin
      - DATABASE_URL=postgres://midas@db/midas
      - DATASTORE=local
      - LOG_LEVEL=silly
      - PORT=3000
      - SAILS_SECRET=just_for_testing_yo
      - 'VCAP_APPLICATION={ "uris": [ "openopps-test.18f.gov" ] }'
      - RUNNING_IN_DOCKER_FOR_DEVELOPMENT=yup
  db:
    image: postgres:9.3
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=midas
      - POSTGRES_USER=midas
volumes:
  node-modules:
  pgdata:
