version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - node-modules:/app/node_modules/
    working_dir: /app
    command: npm run watch
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - PATH=/app/node_modules/.bin:$PATH
      - DATABASE_URL=postgres://midas@db/midas
      - DATASTORE=postgresql
      - LOG_LEVEL=silly
      - PORT=3000
      - SAILS_SECRET=just_for_testing_yo
      - 'VCAP_APPLICATION={ "uris": [ "openopps-test.18f.gov" ] }'
  # README: Initialize the database so that Sails can connect to it.
  init_db:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./tools/postgres/init.sh
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://midas@db/midas
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:9.3
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=midas
      - POSTGRES_USER=midas
volumes:
  node-modules:
  pgdata:
