version: 2
jobs:
  build:
    working_directory: ~/openopps/openopps-platform
    parallelism: 4
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DB_OWNER: ubuntu
      DB_USER: midas
      DB_PASSWORD: midas
      VCAP_APPLICATION: '{ "uris": [ "openopps-test.opm.gov" ] }'
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - run: if [[ `npm -v` != 5* ]]; then npm i -g npm@5.4.2; fi
      - run: rm -rvf node_modules
      - run: npm install
      - run: npm test