version: 2
jobs:
  build:
    working_directory: ~/openopps/openopps-platform
    parallelism: 4
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DB_OWNER: ubuntu
      DB_USER: midas
      DB_PASSWORD: midas
      VCAP_APPLICATION: '{ "uris": [ "openopps-test.opm.gov" ] }'
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
      - checkout
      - run: nvm install 8.6.0 && nvm alias default 8.6.0
      - run: if [[ `npm -v` != 5* ]]; then npm i -g npm@5.4.2; fi
      - run: rm -rvf node_modules
      - run: npm install