version: 2
jobs:
  build:
    working_directory: ~/openopps/openopps-platform
    parallelism: 4
    environment:
      CC_TEST_REPORTER_ID: 42b393f57b62cc7ac9c7306746e82672ac4ffe1d5a82995fc28f442cf274be28
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DB_OWNER: ubuntu
      DB_USER: midas
      DB_PASSWORD: midas
      VCAP_APPLICATION: '{ "uris": [ "openopps-test.opm.gov" ] }'
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - run: if [[ `npm -v` != 5* ]]; then npm i -g npm@5.4.2; fi
      - run: rm -rvf node_modules
      - run: npm install
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: 
        name: test
        command: npm run cover:unit
      - run: ./cc-test-reporter after-build --exit-code $?
      - store_test_results:
          path: /tmp/circleci-test-results
